[package]
name = "filenamefix"
version = "0.1.0"
authors = ["docoder <docoder@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1"
